#!/usr/bin/env bash

check_root() {

  if groups | grep -Eq "\broot\b"; then
    return 0
  elif groups | grep -Eq "\bsudo\b"; then
    printf '%b' 'sudo'
  else
    breake
  fi
}

cmd_prefix=$(check_root)

if [[ $cmd_prefix = 'sudo' ]]; then
  alias apt='sudo apt'
  alias dpkg-query='sudo dpkg-query'
fi

install() {
  local apps_to_install app prefix

  prefix=$(check_root)

  # shellcheck disable=SC2068
  for app in ${@}; do
    [[ -z $(dpkg-query -l | grep -E "\b$app\b" | cut -d " " -f3) ]] && apps_to_install+=("$app")
  done
  
  # shellcheck disable=SC2068
  [[ -n "${apps_to_install[*]}" ]] && apt install ${apps_to_install[@]} -y --no-install-recommends

}

update() {
  local prefix
  prefix=$(check_root)
    prefix apt update 2>&1>/dev/null | grep -qE "^[[:digit:]]+.*?packages" && prefix apt upgrade -y
}
