#!/usr/bin/env bash

shopt -s expand_aliases

check_root() {

  if groups | grep -Eq "\broot\b"; then
    return 0
  elif groups | grep -Eq "\bsudo\b"; then
    printf '%b' 'sudo'
  else
    prinf '%s' 'restrict'
  fi
}

cmd_prefix=$(check_root)

if [[ $cmd_prefix = 'sudo' ]]; then
  alias apt='sudo apt'
  alias dpkg-query='sudo dpkg-query'
  sudo -b printf '%s' ''
elif [[ $cmd_prefix = 'restrict' ]]; then
  exit 4
fi

install() {
  local apps_to_install

  # shellcheck disable=SC2068
  for app in ${@}; do
    [[ -z $(dpkg-query -l | grep -E "\b$app\b" | cut -d " " -f3) ]] && apps_to_install+=("$app")
  done
  
  # shellcheck disable=SC2068
  [[ -n "${apps_to_install[*]}" ]] && apt install ${apps_to_install[@]} -y --no-install-recommends

}

update() {
    apt update 2>&1>/dev/null | grep -qE "^[[:digit:]]+.*?packages" && apt upgrade -y
}
