#!/usr/bin/env bash
source ./local_env

country=$(./extras/my_country)
release=$(lsb_release -cs)

[[ -z ${country} ]] && country='en'

# ToDo: Сделать проверку доступности локального скопа репозиториев

source_file="/etc/apt/sources.list"
session_timestamp="$(date +"%Y%m%d-%H%M%S")"

[[ -f "${source_file}" ]] && {
  cp "${source_file}" "${source_file}_${session_timestamp}.backup"
}

check_file_protection "${source_file}" && {
  tee "${source_file}" >/dev/null 2>&1 <<EOF
# protected
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release} main restricted
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release}-updates main restricted
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release} universe
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release}-updates universe
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release} multiverse
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release}-updates multiverse
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release}-backports main restricted universe multiverse
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release}-security main restricted
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release}-security universe
deb [arch=amd64] http://${country}.archive.ubuntu.com/ubuntu ${release}-security multiverse
EOF
}
update
install software-properties-common htop lnav curl wget links ncdu python3-{dev,pip,venv} mc snapd jq resolvconf acl

fix_wait_online
