#!/usr/bin/env bash
source ./activate

install software-properties-common htop lnav curl wget links ncdu

add-apt-repository ppa:deadsnakes/ppa -y > /dev/null 2>&1

update
install python3-{dev,pip,venv}
