#!/usr/bin/env bash

# shellcheck disable=SC2068
for app in ${@}; do
  [[ -z $(sudo dpkg-query -l | grep -E "\b$app\b" | cut -d " " -f3) ]] && apps_to_install+=("$app")
done

[[ -n "${apps_to_install[*]}" ]] && sudo apt install ${apps_to_install[@]} -y --no-install-recommends
