#!/usr/bin/env bash

cd "$(dirname "$0")" && source ../local_env || exit 20

default_directives='Port 12982
PermitRootLogin no
ClientAliveInterval 5
ClientAliveCountMax 30
PasswordAuthentication no'

printf 'Preset directives:\n\n%b\n' "${default_directives[@]}"
echo

read -r -p 'Want to change directives? [y|N]: ' -n 1 reply
echo

if [[ "${reply,,}" = 'y' ]]; then
  while read -r -u 3 directive; do

    read -r name value <<<"$directive"

    printf '%s = ' "${name}"
    read -r reply

    [[ -n $reply ]] && value=$reply

    directives+=("${name} ${value}")

  done 3< <(printf '%s\n' "${default_directives}")

else

  directives=("${default_directives[@]}")
fi

printf '%b\n' "${directives[@]}" | tee /etc/ssh/sshd_config.d/override.conf

systemctl restart sshd
