#!/usr/bin/env bash

cd "$(dirname "$0")" && source ../local_env || exit 20

default_directives='Port 12982
PermitRootLogin no
ClientAliveInterval 5
ClientAliveCountMax 30
PasswordAuthentication no'

printf '%b\n' "${default_directives[@]}"
echo

read -r -p 'Want to change directives? [y|N]: ' -n 1 reply
if [[ "${reply,,}" = 'y' ]]; then
  while read -r -u 3 directive; do

    read -r name value <<<"$directive"

    printf '%s = ' "${name}"
    read -r reply

    [[ -n $reply ]] && value=$reply

    new_directives+=("${name} ${value}")

  done 3< <(printf '%s\n' "${default_directives}")

  printf '%b\n' "${new_directives[@]}" | tee ../override.conf
else
  printf '%b\n' "${default_directives[@]}" | tee ../override.conf
fi
