#!/usr/bin/env bash

cd "$(dirname "$0")" && source ../local_env || exit 20

default_directives='Port 12982
PermitRootLogin no
ClientAliveInterval 5
ClientAliveCountMax 30
PasswordAuthentication no'

while read -r -u 3 directive; do

  read -r name value <<<"$directive"

  printf '%s = ' "${name}"
  read -r reply

  [[ -n $reply ]] && value=$reply

  new_directives+=("${name} ${value}")

done 3< <(printf '%s\n' "${default_directives}")

[[ -z "${new_directives[*]}" ]] && new_directives="$default_directives"

printf '%b\n' "${new_directives[@]}"
