#!/usr/bin/env bash
shopt -s expand_aliases

cd "$(dirname "$0")" || exit

source ../activate

cmd_prefix=$(check_root)

if [[ $cmd_prefix = 'sudo' ]]; then
  alias tee='sudo tee'
  alias gpg='sudo gpg'
fi

[[ -n "$1" ]] && version="$1" || version=15

[[ -z ${version} ]] && exit 2

keypath="/usr/share/keyrings/pgdg-${version}.gpg"

release=$(lsb_release -cs)

if [[ ! -f ${keypath} ]]; then
  curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o "${keypath}"
  tee /etc/apt/sources.list.d/pgdg-"${version}".list <<EOF
deb [signed-by=${keypath} arch=amd64] http://apt.postgresql.org/pub/repos/apt ${release}-pgdg main
EOF
fi

update
install postgresql-"${version}" postgresql-client-"${version}" libpq-dev postgresql-"${version}"-mysql-fdw
